[config]
rpc = "https://fullnode.testnet.sui.io:443"

[packages]
AMM = { local = "../../../move/amm" }
Examples = { local = "../../../move/examples" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.62.1", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.62.1", override = true }
